---
- hosts: linuxservers
  become: true
  gather_facts: true

  tasks:
    - name: Ping Host
      ansible.builtin.ping:
    - name: Get OS information
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
