---
- hosts: linuxservers
  become: true
  gather_facts: true

  tasks:
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
    - name: Print OS information
      debug:
        msg: "Host {{ inventory_hostname }} is running {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"
