---
- hosts: linuxservers
  become: true
  tasks:
      - name: Update package cache (apt or yum)
        apt:
          update_cache: yes
        when: ansible_pkg_mgr == 'apt'
        yum:
          update_cache: yes
        when: ansible_pkg_mgr == 'yum'
  
      - name: Upgrade all packages
        apt:
          name: '*'
          state: latest
        when: ansible_pkg_mgr == 'apt'
        yum:
          name: '*'
          state: latest
        when: ansible_pkg_mgr == 'yum'
  
      - name: Check if reboot is required (Debian/Ubuntu)
        stat:
          path: /var/run/reboot-required
        register: reboot_required_file
        when: ansible_os_family == 'Debian'
  
      - name: Reboot if required (Debian/Ubuntu)
        reboot:
        when: reboot_required_file.stat.exists
  
      - name: Check if reboot is required (RedHat)
        command: needs-restarting -r
        register: needs_restarting_result
        changed_when: "'needs restarting' in needs_restarting_result.stdout"
        when: ansible_os_family == 'RedHat'
  
      - name: Reboot if required (RedHat)
        reboot:
        when: needs_restarting_result.changed
